-- DROP ALL TABLE FIRST
DO $$ 
DECLARE 
    r RECORD;
BEGIN 
    FOR r IN (SELECT tablename FROM pg_tables WHERE schemaname = 'public') LOOP
        EXECUTE 'DROP TABLE IF EXISTS ' || quote_ident(r.tablename) || ' CASCADE';
    END LOOP; 
END $$;

-- Enums
DROP TYPE IF EXISTS pmt_method;
DROP TYPE IF EXISTS system_req;
CREATE TYPE pmt_method AS ENUM ('promptpay', 'mastercard', 'visa', 'truemoney');
CREATE TYPE system_req AS ENUM ('min', 'recommended');

-- Tables
CREATE TABLE products (
    product_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) NOT NULL UNIQUE,
    description TEXT NOT NULL, -- TEXT is preferred over VARCHAR(1024) in Postgres
    price DECIMAL(10, 2) NOT NULL,
    poster_url VARCHAR(512) NOT NULL
);

CREATE TABLE categories (
    category_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) NOT NULL UNIQUE,
    is_hidden BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE TABLE accounts (
    user_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(50) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    created_date DATE NOT NULL DEFAULT CURRENT_DATE,
    total_spend DECIMAL(10, 2) DEFAULT 0,
    total_game INT DEFAULT 0,
    total_sale DECIMAL(10, 2) DEFAULT 0
);

CREATE TABLE hardware_requirement (
    requirement_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    operating_system VARCHAR(50) DEFAULT '-',
    processor VARCHAR(50) DEFAULT '-',
    memory VARCHAR(50) DEFAULT '-',
    graphics_card VARCHAR(50) DEFAULT '-',
    directx_version VARCHAR(50) DEFAULT '-',
    network VARCHAR(50) DEFAULT '-',
    storage VARCHAR(50) DEFAULT '-',
    soundcard VARCHAR(50) DEFAULT '-',
    additional_note VARCHAR(255) DEFAULT '-',
    type system_req,
    product_id INT NOT NULL REFERENCES products(product_id) ON DELETE CASCADE
);

CREATE TABLE images (
    image_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    image_url VARCHAR(255),
    product_id INT NOT NULL REFERENCES products(product_id) ON DELETE CASCADE
);

CREATE TABLE videos (
    video_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    video_url VARCHAR(255),
    product_id INT NOT NULL REFERENCES products(product_id) ON DELETE CASCADE
);

CREATE TABLE orders (
    order_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INT NOT NULL REFERENCES accounts(user_id) ON DELETE CASCADE,
    order_date DATE NOT NULL DEFAULT CURRENT_DATE,
    payment_method pmt_method NOT NULL,
    final_price DECIMAL(10, 2) NOT NULL
);

CREATE TABLE order_items (
    order_id INT NOT NULL REFERENCES orders(order_id) ON DELETE CASCADE,
    product_id INT NOT NULL REFERENCES products(product_id) ON DELETE RESTRICT,
    PRIMARY KEY (order_id, product_id)
);

CREATE TABLE wishlists (
    user_id INT NOT NULL REFERENCES accounts(user_id) ON DELETE CASCADE,
    product_id INT NOT NULL REFERENCES products(product_id) ON DELETE RESTRICT,
    wishlist_date DATE NOT NULL DEFAULT CURRENT_DATE,
    PRIMARY KEY (user_id, product_id)
);

CREATE TABLE carts (
    user_id INT NOT NULL REFERENCES accounts(user_id) ON DELETE CASCADE,
    product_id INT NOT NULL REFERENCES products(product_id) ON DELETE CASCADE,
    cart_date DATE NOT NULL DEFAULT CURRENT_DATE,
    PRIMARY KEY (user_id, product_id)
);

CREATE TABLE product_lists (
    list_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id INT NOT NULL REFERENCES products(product_id) ON DELETE CASCADE,
    category_id INT REFERENCES categories(category_id) ON DELETE SET NULL,
    user_id INT NOT NULL REFERENCES accounts(user_id) ON DELETE RESTRICT,
    release_date DATE NOT NULL
);

CREATE TABLE sessions (
    session_id VARCHAR(128) PRIMARY KEY,
    expires TIMESTAMPTZ NOT NULL, -- Using Timestamptz for better time management
    data TEXT -- Standard Postgres text handles UTF-8 by default
);