spring.application.name=kd5fbackend
server.servlet.context-path=/api

# Database Connection
spring.datasource.url=jdbc:postgresql://localhost:5432/kd5f
spring.datasource.username=kd5f
spring.datasource.password=123

# Hibernate properties
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect